version: '1.0'

services:
  api1: &api
      build:
          context: .
          dockerfile: ./Dockerfile
      image: dominus04/rinha2023
      hostname: api1
      depends_on:
        - postgres
      expose:
          - 80
      restart:
        on-failure
      deploy:
          resources:
              limits:
                  cpus: '0.5'
                  memory: '1GB'

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: python_test
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2GB'
