version: '1.0'

services:
  api1: &api
      build:
          context: .
          dockerfile: ./Dockerfile
      # image: dominus04/rinha2023'
      hostname: api1
      environment:
        HTTP_PORT: 8080
      network_mode: host
      container_name: api1
      depends_on:
        postgres:
          condition: service_healthy
      restart:
        on-failure
      deploy:
          resources:
              limits:
                  cpus: '0.5'
                  memory: '0.75GB'

  api2:
    <<: *api
    hostname: api2
    container_name: api2
    environment:
      HTTP_PORT: 8081

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    network_mode: host
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: python_test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d python_test -U postgres"]
      interval: 10s
      start_period: 10s
      timeout: 5s
      retries: 5
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1GB'
